/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/router';
import { useGLTF, useAnimations, Html } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { useFrame } from '@react-three/fiber';
import lerp from 'lerp';

export default function Cam({ step }) {
    // useFrame(({ clock, camera, v = new THREE.Vector3() }) => {
    //     camera.position.lerp(v.set(zoom ? 0.4 : 11.4, zoom ? 1.2 : 2.8, zoom ? 1.2 : 6.2), 0.05);
    // });
    // const cam = useThree();

    useFrame(({ clock, camera, v = new THREE.Vector3() }) => {
        camera.position.lerp(v.set(0.75, 1, 1.25), 0.05);
    });

    return null;
}
