/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: dithyapr1 (https://sketchfab.com/dithyapr1)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/stitch-5f5118a1443a4047ab6e3142060bc235
title: Stitch
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
    nodes: {
        Object_4: THREE.Mesh;
        Object_5: THREE.Mesh;
    };
    materials: {
        ['initialShadingGroup.001']: THREE.MeshBasicMaterial;
        ['lambert2SG.001']: THREE.MeshBasicMaterial;
    };
};

export default function Stitch({ ...props }: JSX.IntrinsicElements['group']) {
    const group = useRef<THREE.Group>();
    const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult;
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
                        <mesh geometry={nodes.Object_4.geometry} material={materials['initialShadingGroup.001']} />
                        <mesh geometry={nodes.Object_5.geometry} material={materials['lambert2SG.001']} />
                    </group>
                </group>
            </group>
        </group>
    );
}

useGLTF.preload('/scene.gltf');
